name: Assignment1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPWD }}" | docker login -u "punitjain17" --password-stdin
        docker image build -t punitjain17/assigment:latest .
        docker push punitjain17/assignment:latest
      
